### ISSUE TITLE
`invoices/set_estimate_status` not accessible

### ISSUE THREAD

**Issue by kirillbunin** [superfaktura/docs#11]
API endpoint `invoices/set_estimate_status` which is used in the website client is not allowed for API requests, and there is no alternative in the documentation to achieve the same result.

**Comment by superfaktura** [comment]
Hello,
the problem has been identified and fixed, you can use `invoices/set_estimate_status/{invoice_id}/{status_id}` to change status of estimates
where status_id can be 3 for reject, 2 for approve and 1 for not decided
