### ISSUE TITLE
`invoice/edit` adds new `InvoiceItem` instead of overwritting them.

### ISSUE THREAD

**Issue by kirillbunin** [superfaktura/docs#12]
POST request on `invoice/edit` with `"InvoiceItem"` updates the existing items by adding to them, instead of overwritting them. I don't see an option to enforce overwritting/changing existing InvoiceItems.

**Comment by superfaktura** [comment]
Hello,
to change InvoiceItem, you need to provide its id in request, without id its considered as new item

**Comment by kirillbunin** [comment]
Thanks for the reply. What about deleting existing InvoiceItems?

**Comment by superfaktura** [comment]
You can find endpoint for deleting invoice items here https://github.com/superfaktura/docs/blob/master/invoice.md#delete-invoice-item

**Comment by kirillbunin** [comment]
Semantically it means that the endpoint updates/puts in to the invoice, instead of editting/changing it.
I could justify storing ID of invoice items locally, but having to delete them every time it gets deleted locally is not a sound decision.
You might want to reconsider your endpoints, anytime change occurs at my end, I decided to delete the whole invoice and create a new one, since it ends up being cost effective.

**Comment by superfaktura** [comment]
Thanks for your suggestion
