### ISSUE TITLE
Prepojenie prijatej objednavky a zalohovej faktury

### ISSUE THREAD

**Issue by bpotocnak96** [superfaktura/docs#14]
Ako je mozne pridat k prijatej objednavke prepojenie so zalohovou fakturov?

1, Najskor sa vytvara prijata objednavka a ID sa uchovova
2, Nasledne sa vytvara zalohova faktura, akym sposobom je mozne priradit vyssie ziskane ID aby objednavka bola prepojena so zalohovou fakturou?

**Comment by filip-minarik** [comment]
Ano najskor vytvorite objednavku Invoice.type = order, potom zalohovu fakturu Invoice.type = "proforma" a potom ID oboch dokumentov previazete cez Endpoint https://github.com/superfaktura/docs/blob/master/invoice.md#add-related-item ako je napisane v priklade: 
```
{
  "parent_id": {id_objednavky},
  "parent_type": "invoice",
  "child_id": {id_proforma_faktury},
  "child_type": "invoice"
  }
```
