### ISSUE TITLE
Cannot add expense

### ISSUE THREAD

**Issue by EskelCz** [superfaktura/docs#2]
I'm trying to use the example request for adding expense and I cannot make it work.
```
curl POST \
    -d "data={'Expense':{'name':'Foo bar','currency':'CZK','amount':12.14}}" \
    https://moje.superfaktura.cz/expenses/add
```
(plus authentication header) is returning this error: `{"error":1,"error_message":{"name":"Toto pole nem\u016f\u017ee b\u00fdt pr\u00e1zdn\u00e9"}}`

I've tried the same thing with node.js request and for some reason the error is different but essentially the same meaning: `{ error: 1, message: 'Chybějící údaje', error_message: 'Chybějící údaje' }`

Can you please replicate this with the curl command? Many thanks.

**Comment by superfaktura** [comment]
Hello,

the problem is that your data is not valid JSON. You have to use double quotes (you can check on here: https://jsonlint.com).
So your data option should look like:
```
-d 'data={"Expense":{"name":"Foo bar","currency":"CZK","amount":12.14}}'
```
instead of
```
-d "data={'Expense':{'name':'Foo bar','currency':'CZK','amount':12.14}}" 
```

If you want to test with curl, also don't forget to add authentication header and `-X` or `--request` before POST :)

**Comment by EskelCz** [comment]
Thanks, that's one part, the second is probably this issue:
https://stackoverflow.com/questions/31954022/npm-request-module-body-vs-json
I was adding the json to the request body, without stringifying it.
My first http code, sorry :)

**Comment by EskelCz** [comment]
@superfaktura Still, when sending this data as a string in body of the request:
{"Expense":{"name":"Name","currency":"CZK","amount":"7650"}}

I'm getting this response:  "Chyb\\u011bj\\u00edc\\u00ed \\u00fadaje"

I'm trying to use 'request' module which offers only `body`. The curl command uses `data`, so I'm confused, is there a difference?

**Comment by EskelCz** [comment]
@superfaktura Still, I'm having the same problem when I'm sending the same (valid) JSON data from javascript code.

I'm trying two variants:

Request body: `{"Expense":{"name":"David Spohr","currency":"CZK","amount":"7650"}}`
Response: `{ error: 1, message: 'Chybějící údaje', error_message: 'Chybějící údaje' }`

Request body: `data={"Expense":{"name":"Test Name","currency":"CZK","amount":"7650"}}`
Response: `"Chyb\\u011bj\\u00edc\\u00ed \\u00fadaje"`

**Comment by superfaktura** [comment]
I am not sure what options JavaScript fills automatically, but my guess was a Content-Type issue.
Probably JS sets `Content-Type: application/json` by default.
This assumption seems to be correct, considering the provided example, which did work correctly.

Notice `Content-Type` header and the format of body (POST data).
When I commented `Content-Type` line, it did not work, just as you reported.

```
(async () => {
  const rawResponse = await fetch('https://moje.superfaktura.cz/expenses/add', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
      'Authorization': 'SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id='
    },
    body: 'data={"Expense":{"name":"Foo bar","currency":"CZK","amount":12.14}}'
  });
  const content = await rawResponse.json();

  console.log(content);
})();
```


Please let us know if it worked. Until then issue remains open.

**Comment by EskelCz** [comment]
@superfaktura That was the issue, exactly. Thank you!

**Comment by EskelCz** [comment]
I’m getting this error again, without any significant change on my part (except api key). Have you changed something recently?

**Comment by superfaktura** [comment]
Hi,
no, no changes done to this part. I just checked, and everything works fine for me.

Request:
```
curl -X POST \
    -H "Authorization: SFAPI email=USER%40EMAIL&apikey=API_KEY&company_id=COMPANY_ID" \
    -d 'data={"Expense":{"name":"Foo bar baz","currency":"CZK","amount":12.14}}' \
    https://moje.superfaktura.cz/expenses/add
```

When we are done investigating what's wrong, we will let you know.

**Comment by EskelCz** [comment]
The issue was a new line symbol in final urlencoded json: %0A
Thanks for reaching out and helping me resolve it.
I just wish the error messages would be more detailed.

**Comment by superfaktura** [comment]
@EskelCz We have added validation error message, when sent JSON is invalid.
The text in parentheses comes from JSON decode function.

Here is an example:
```
{
   "error" : 1,
   "message" : "Zlý formát dát (Syntax error)",
   "error_message" : "Zlý formát dát (Syntax error)"
}
```
