### ISSUE TITLE
Adding a client to expense

### ISSUE THREAD

**Issue by EskelCz** [superfaktura/docs#3]
I found in your docs how to find/add a client, but I don't see how to assign the client to an invoice.

I'm creating an almost fully automated invoicing system, from paper to AI OCR system, from AI to your service, and lastly to the bank with batch payment. This is the last step missing, but crucial. I need to find a way to do it.

Basically I would expect the addExpense method to allow for a client_id attribute. Maybe it's undocumented?

Thank you.

**Comment by superfaktura** [comment]
You are right, specifying `client_id` is enough for an existing client.

```
data='{
    "Invoice":{
        "name": "Test API",
        "client_id": 431
    },
    "InvoiceItem":[
        {
            "description": "description of item 1",
            "name": "item 1",
            "tax": 20,
            "unit_price": 10
        }
    ]
}';

curl -X POST \
    -d "data=$data" \
    -H "Authorization: SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id=" \
    https://moje.superfaktura.cz/invoices/create
```


You can also specify a new client like so:
```
data='{
    "Invoice":{
        "name": "Test API"
    },
    "InvoiceItem":[
        {
            "description": "description of item 1",
            "name": "item 1",
            "tax": 20,
            "unit_price": 10
        }
    ],
    "Client": {
        "ico": "46655034",
        "name": "SuperFaktura.sk"
    }
}';

curl -X POST \
    -d "data=$data" \
    -H "Authorization: SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id=" \
    https://moje.superfaktura.cz/invoices/create
```
Where in `Client` key you can specify attributes like in client creation itself (https://github.com/superfaktura/docs/blob/master/clients.md#attributes). Creating client separately sounds like the cleaner way though :)

**Comment by EskelCz** [comment]
@superfaktura Thanks for the reply but I'm confused, I need to add the client to an **expense** invoice (addExpense method), where I don't see the client_id attribute in documentation.
https://github.com/superfaktura/docs/blob/master/expenses.md#add-expense

Is that a limitation of your api, or an undocumented option? (I'll go test it out now)

**Comment by superfaktura** [comment]
I was reading about Invoice, so added an invoice example.
The same applies for expenses as well.

```
data='{"Expense":{"name":"Foo bar baz","currency":"CZK","amount":12.14,"client_id":431}}';

curl -X POST \
    -d "data=$data" \
    -H "Authorization: SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id=" \
    https://moje.superfaktura.cz/expenses/add
```

Or you can add new client while adding expense:
```
data='{"Expense":{"name":"Foo bar baz","currency":"CZK","amount":12.14}, "Client":{"name":"VW","ico":35757442}}';

curl -X POST \
    -d "data=$data" \
    -H "Authorization: SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id=" \
    https://moje.superfaktura.cz/expenses/add
```


Thank you for reporting missing attribute, will add it to expense documentation.

**Comment by EskelCz** [comment]
@superfaktura Awesome, that's a great relief, thank you!

**Comment by EskelCz** [comment]
@superfaktura Just one more question. :) When I try run the second example (adding a client) and the ičo already exists, will you find the existing client data for that ičo and set the right client_id to the invoice or will it throw an error?
(I'm assuming ico can be used as a unique identifier)

I can resolve it with a prior request and search the client list, it would just be more work on my part.
Thanks.

**Comment by superfaktura** [comment]
You are right, it will use the existing client.

**Comment by EskelCz** [comment]
Perfect, thanks

**Comment by EskelCz** [comment]
@superfaktura Seems like we've hit on some kind of a bug in this process and some clients started to appear twice or more, in contacts. They have the same name and IČ.

It's making it harder to search for invoices. They are displayed as ContactName(1) and ContactName(2).
We would absolutely prefer to have them merged by the IČ value, regardless of the name string.

Should I contact you over the support email about this?

**Comment by superfaktura** [comment]
We want to let you know that we will have to investigate this issue further. Once we get results, we will contact you back - either here or by support email - based on the nature of the problem.

**Comment by superfaktura** [comment]
Responded via e-mail.
The problem seems to be in requests construction, in 3rd party service.
