### ISSUE TITLE
Expense: Adding total amount

### ISSUE THREAD

**Issue by EskelCz** [superfaktura/docs#4]
One more issue on my journey to full automation. :) Everything is working great except for adding money values.

The problem is, sometimes expense invoices have multiple items with different tax rates. That's a pain to be adding all those separately but I guess it can be done. Your web UI allows this, but I don't see the option in the API.

My preferred solution would be simpler though. I don't really need to list every single item and value, I only need the grand total to be paid. Again, this is done well in the web UI where you can add the final amount **with** tax, but in the API docs I see only total amount **without** tax and a single tax rate.

Is this something you can support? To add something like `amount_total`?

Otherwise it's bound to create differences in total amounts and create a mess in actual money transactions. Therefore making the whole solution counterproductive.
Thank you for your consideration.

**Comment by superfaktura** [comment]
Good to hear everything else is working great :)

I am a little bit confused here. Do you mean expenses or invoices? When you say, it works so in our web UI, I would say it's invoices (https://moje.superfaktura.cz/invoices/).

If so, you can specify custom tax (VAT) for each item.
You can see it in attributes for InvoiceItem in AddInvoice method documentation (https://github.com/superfaktura/docs/blob/master/invoice.md#invoiceitem-1)
Example:
```
data='{
    "Invoice":{
        "name": "Test API"
    },
    "InvoiceItem":[
        {
            "description": "description of item 1",
            "name": "item 1",
            "tax": 21,
            "unit_price": 10
        },
        {
            "name": "item 2",
            "tax": 10,
            "unit_price": 20
        }
    ],
    "Client":{
        "id": "513"
    }
}';

curl -X POST \
    -d "data=$data" \
    -H "Authorization: SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id=" \
    https://moje.superfaktura.cz/invoices/create
```

In the response you will see
```
        "Summary": {
            "discount": 0,
            "invoice_total": 34.1,
            "vat_base_separate": {
                "10": 20,
                "21": 10
            },
            "vat_base_total": 30,
            "vat_separate": {
                "10": 2,
                "21": 2.1
            },
            "vat_total": 4.1
        },
```

If you really need to specify custom total amount, you can do the math on client side. So, if you know the total price will be 121, you will send 100 (without VAT, considering default VAT is 21%) and it fits.
The potentially bad thing about this approach is float numbers representation and different types of VAT calculation (https://github.com/superfaktura/docs/blob/master/value-lists.md#rounding-types or in web UI https://moje.superfaktura.cz/users/edit_profile/settings > "Rounding method"). So we really recommend sending VAT for each item separately to avoid possible problems.

Based on our internal logic, we are not supporting specifying total amount with VAT.

**Comment by EskelCz** [comment]
@superfaktura I'm also confused, why this misunderstanding came up for the third time, as with the previous issues I opened.

I'm talking about **received** invoices, which are an expense for the business. That means **Expense** on your web and in API docs. The doc for expenses is much shorter and feels a little unfinished, although it deals with basically the same thing as invoices *issued*. There is no mention how to add items for example.
(Is it the same as in the Invoice doc? If so, I'm not sure why would you have two separate documents and have such a big difference between them.)

Anyway, I'm talking about the web UI at [moje.superfaktura.cz/expenses/add](https://moje.superfaktura.cz/expenses/add) which is a little different as well. As a user, for received invoice you don't really want to retype all items, there is no need. You want mainly to store the value to be paid, and issue a batch bank order. (At least that's the use case for my client)
Accordingly, your web UI is great that it allows just adding the total amount for expense, without having to sort through meaningless details and it's one of the reasons why we've chosen your service instead of others.

It's the same problem with AI. It can read the invoice items effortlessly, but it might make a mistake and it have to be checked and corrected, which again is needlessly adding time and effort to the processing task. Better not to have to add all items at all, just to add the total amount, which we already have (calculated by the issuer) on the received invoice.

I'm not sure why would you want your API to behave differently than your website.
You probably already have the logic for this, this might be a feature request to expose it in the API.
Thanks for your consideration.

**Comment by superfaktura** [comment]
For expense it is just as you said in the beginning - in order to simplify things, you don't specify each item separately.
If you have different VAT rates, you can send up to 3 of them with their corresponding amounts.

Here is a couple of examples:

```
# this will create an expense with total price 121 CZK, 0% VAT
data='{
    "Expense":{
        "name":"Expense with VAT",
        "currency": "CZK",
        "amount":121
    }
}';


# this will create an expense with total price with VAT 331 CZK, 3 different tax rates
data='{
    "Expense":{
        "name":"Expense with VAT",
        "currency": "CZK",
        "vat": 21,
        "amount": 100,
        "vat2": 10,
        "amount2": 100,
        "vat3": 0,
        "amount3": 100
    }
}';


curl -X POST \
    -d "data=$data" \
    -H "Authorization: SFAPI email=api%40example.com&apikey=c0a4cdcdfe98ca660942d60cf7896de6&company_id=" \
    https://moje.superfaktura.cz/expenses/add
```

Documentation is updated with missing attributes.

We will gladly help you with concrete use case, if you need - just write us to info@superfaktura.sk. :)

**Comment by EskelCz** [comment]
Ok, thanks, moving the conversation to email.
