### ISSUE TITLE
Adding attachment to expense

### ISSUE THREAD

**Issue by EskelCz** [superfaktura/docs#5]
Is it possible to add an attachment with API?
I see the possibility in the web UI. I'd like to send the expense document pdf along with the parsed data, for later reference if need be.
Thanks

**Comment by superfaktura** [comment]
Hello,
no, currently it is not possible to add an attachment via API.

**Comment by EskelCz** [comment]
@superfaktura Thanks for the information, but I could really use this. I imagine it shouldn't be too difficult to to allow a formData request for it, since you already have the option on the website.

Do you have a process for feature requests? I'd like to open one.

In return I can open source a connector code I've written, between your service and [Rossum.ai](https://rossum.ai/cz/), a czech startup for automating reading of invoices.
Maybe even write a blog post about how to set it up with SF.

**Comment by superfaktura** [comment]
Sorry it took a while, there was some discussion about this issue.
The possibility of publishing Rossum connector sounds very interesting :)
Is there a possibility to see / test it anywhere? If it's not public yet, you could post privately to info@superfaktura.cz.

We will add possibility to upload attachments to our plan.

**Comment by superfaktura** [comment]
@EskelCz good news - support for attachment is added, you can see updated docs on https://github.com/superfaktura/docs/blob/master/expenses.md#add-expense :)

**Comment by EskelCz** [comment]
@superfaktura That's awesome, thank you! :)
I'll implement it to the connector and make the public release and blog post.

**Comment by EskelCz** [comment]
@superfaktura As promised, here is the connector code and basic usage description:
https://github.com/EskelCz/superfaktura-elis-connector
I'm also in contact with Rossum, trying to make it official, to make it easier to set up.
Once we figure it out I'll make a blog post for people to follow.
