### ISSUE TITLE
email adresa obsahuje znak "+"

### ISSUE THREAD

**Issue by kodl** [superfaktura/docs#6]
Dobrý den, dle definice emailová adresa může obsahovat znak "+" - při použití vašeho API `/clients/create` však dojde k chybě, pokud emailová adresa tento znak obsahuje.

Prosím o ověření a nápravu

Děkuji

**Comment by superfaktura** [comment]
Dobrý deň,
viete nám prosím poslať celý request aj s chybovou hláškou na info@superfaktura.cz, pretože testoval som vytvorenie klienta s emailovou adresou obsahujúcou + a request prebehol v poriadku.

**Comment by kodl** [comment]
Dobrý den, níže zasílám příklady requestů, u kterých se nám vrací chyba ..

RESPONSE: `errror: { email: [ 'Zadajte platnú emailovú adresu, prosím.' ] },`

reqBody: `data={"Client":{"name":"Súkr. MŠ INškôlka","ico":"859","dic":"98898","iban":"9895","email":"hasek.dav+d1@gmail.com","address":"Cintorínska 7669/7","city":"Bratislava-Staré Mesto","zip":"81108","country":"Slovensko"}}`

reqBody: `data={"Client":{"name":"Súkr. MŠ INškôlka","ico":"xxxxxx","dic":"xxxxxx","iban":"xxxxxx","email":"test.test+neco@gmail.com","address":"Cintorínska 7669/7","city":"Bratislava-Staré Mesto","zip":"81108","country":"Slovensko"}}`

reqBody: `data={"Client":{"name":"Súkr. MŠ INškôlka","ico":"pp","dic":"pp","iban":"pp","email":"hasek.david+1@gmail.com","address":"Cintorínska 7669/7","city":"Bratislava-Staré Mesto","zip":"81108","country":"Slovensko"}}`

reqBody: `data={"Client":{"name":"Súkr. MŠ INškôlka","ico":"o","dic":"o","iban":"o","email":"ha+sek.david@gmail.com","address":"Cintorínska 7669/7","city":"Bratislava-Staré Mesto","zip":"81108","country":"Slovensko"}}`

reqBody: `data={"Client":{"name":"Súkr. MŠ INškôlka","ico":"9620920","dic":"9620920","iban":"9620920","email":"hasan+advud1@gmail.com","address":"Cintorínska 7669/7","city":"Bratislava-Staré Mesto","zip":"81108","country":"Slovensko"}}`

S pozdravem KŠ

**Comment by superfaktura** [comment]
Tie emaily sú v poriadku. Skôr to vypadá na nejaký problém implementácie(v niektorych prípadoch môže byť + reprezentované ako medzera). Prosím Vás napíšte nám na support info@superfaktura.cz aby sme Vás vedeli identifikovať a pozreli sa ako k nám chodia requesty.

**Comment by jakubcin** [comment]
Dobry den, mam rovnaky problem, napr. so znakmi '&' a '+', je vhodne posielat hodnoty v json s pouzitim encodeURIComponent alebo je potrebne riesit to inym sposobom ?

**Comment by superfaktura** [comment]
Ano, odporucame pouzit `encodeURIComponent`.
